version: '3.8'

services:
  openresty:
    image: openresty/openresty:alpine
    container_name: openresty01
    ports:
      - "8090:8090"
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf/conf.d/:/usr/local/openresty/nginx/conf/conf.d/
      - ./lua:/usr/local/openresty/nginx/lua
      - ./logs:/usr/local/openresty/nginx/logs
    # depends_on:
      # - backend
    networks: 
      - common-network
    # network_mode: host
    restart: unless-stopped

  # backend:
  #   build: ./backend
  #   container_name: cdn-backend
  #   networks:
  #     - common-network
  #   restart: unless-stopped

networks:
  common-network:
    driver: bridge
