version: '3.8'

services:
  base_project-admin:
    image: registry.xxx.net:9191/projectname/base_project:latest
    container_name: base_project
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.yaml:/app/config.yaml
      - ./logs:/app/logs
    command: ["/app/base_project", "start", "-c", "/app/admin.yaml"]
